@startuml Основной процесс взаимодействия (new)

|Пользователь (не авторизованный)|
start 
:Зашел на сайт;

if (Есть ли у пользователя аккаунт?) then (нет)
    :Регистрация;

    |Система|
    :Проверка данных пользователя;
    if (Удовлетворительны?) then (нет)
        :сообщить пользователю об ошибке;
        stop
    else (да)  
    endif
    :Создание пользователя;
else (да)  
endif

|Пользователь (не авторизованный)|
:Авторизация;

|Система|
:Проверка данных пользователя;
    if (Удовлетворительны?) then (нет)
        :сообщить пользователю об ошибке;
        stop
    else (да)  
    endif
:Авторизация в системе;


'------------------------------ Отображение карты
|Система|
fork
:Запрос на получение местоположения;
    if (Есть права на использование местоположения?) then (нет)
        :запрос на получение прав местоположения;
    else(да)
    endif

|Карта|
fork again
:Отображение карты и местоположения водителя;
|Система|
:Обновить информацию о пользователе;
end fork


'------------------------------ Поиск Парковок
|Водитель|
:Найти близжайщую парковку;
|Система|
:Парковка найдена;
:Отобразить информацию о парковке;
:Отобразить инормацию о расстоянии и маршруте;
'----------------------- Бронь
|Водитель|
:Забронировать место на парковке;
|Система|
:Попытка забронировать место;
    if (Место есть) then (Да)
    :Создать бронь;
    else(Нет)
    :Сообщение о заполненности парковки;
    stop
    endif
:Обновить информацию о парковке;
:Отправить уведомление о создании брони;

|Парковка|
fork
:Бронирование места на n минут;

|Карта|
fork
:Проложить маршрут до парковки;
end fork

|Водитель|
:Подтвердить приезд;

|Система|
fork
:Подтверждение о приезде;
:Отобразить информацию о тарифах парковки;

|Водитель|
:Ввод параметров парковки(Время, тариф);

|Водитель|
:Оплатить место;

|Внешняя система оплаты|
:Произведение оплаты;
:Подтверждение;

|Система|
:Подтверждение брони;
'------------------ Парковочная запись

:Создание парковочной записи;
:Отображение информации о парковочной записи;
|Водитель|
:Показать информацию о записи;

|Система|
:Отображение информации о парковочной записи;

|Парковка|
fork
:Хранение автомобиля заданное время;

|Система|
:Отправка уведомления пользователю об истечении времени парковки;

|Водитель|
:Подтвердить отъезд;

if(Водитель забрал автомобиль вовремя) then(Да)
    
    else(нет)
    |Парковка|
    :Начисление пени за неустойку;
    stop
    endif

|Система|
:Подтверждение отъезда;

|Водитель|
:Освободить место парковки;

|Парковка|
:Запрос оценки оказания услуг;
end fork

|Водитель|
:Указать оценку и отзыв;
end fork

|Система|
:Оценка подтверждена;
end fork



@enduml