@startuml Основной процесс взаимодействия (new)

|Пользователь (не авторизованный)|
start 
:Зашел на сайт;

if (Есть ли у пользователя аккаунт?) then (нет)
    :Регистрация;

    |Система|
    :Проверка данных пользователя;
    if (Удовлетворительны?) then (нет)
        :сообщить пользователю об ошибке;
        stop
    else (да)  
    endif
    :Создание пользователя;
else (да)  
endif

|Пользователь (не авторизованный)|
:Авторизация;

|Система|
:Проверка данных пользователя;
    if (Удовлетворительны?) then (нет)
        :сообщить пользователю об ошибке;
        stop
    else (да)  
    endif
:Авторизация в системе;


'------------------------------ Отображение данных
|Система|
fork
:Запрос на получение данных;

|Домовладелец|
fork again
:Отображение страницы с графиком потребления энергии;

|Администратор| 
fork again
:Отображение страницы с графиком потребления энергии по датчикам(то что есть сейчас в бд);

|Компания| 
fork again
:Отображение страницы с графиком потребления энергии (то что есть сейчас в бд);

|Тех персонал|
fork again
:Отобразить страницу с прекрепленными к нему датчиками и их состояниями;

|Система|
end fork

repeat :Обновление данных;
:Обновление отображения данных;
repeat while (Прошло 5 минут?) is (да) not (нет)


'------------------------------ Установка лимитов
|Система|
fork
:Запрос на установку лимитов;

|Домовладелец|
fork again
:Настроить лимиты;

|Администратор|
fork again
:Настроить лимиты;

|Система|
end fork
:Установить лимиты;

if (Есть превышение лимитов?) then (нет)
else (да)
    '------------------------------ Отправка уведомлений
    |Система|
    fork  
    :Отправить уведомление о превышение лимитов пользователю;

    |Домовладелец|
    fork again
    :Отобразить уведомление;

    |Администратор|
    fork again
    :Отобразить уведомление;

    |Система|
    end fork
endif

    
|Система|
fork 
|Тех персонал| 
fork again
|Система|
if (Есть датчики не в статусе ok или поступил запрос/задача на выполнение работ?) then (нет)
else (да)  
    |Система|
    :Отправить уведомление о наличие датчика в не ok состояние или есть задача;

    |Тех персонал|
    :Отобразить уведомление;

    |Система|
    :Сформулировать задачу;
    :Назначить задачу;
    
    |Тех персонал|
    :Прикрепить отчет о выполнение задачи;
    
    |Система|
    :Сохранить отчет;
endif
end fork

'------------------------------ Аналитика
|Система|
fork
:Сбор данных и подготовка для проведения аналитики;
:Отправить уведомление о наличие рекомендаций пользователю;

|Домовладелец|
fork again
:Запросить рекомендации по оптимизации потребления;
:Отобразить рекомендации;
:Подготовить отчет по потреблению;

|Администратор| 
fork again
:Запрос на получение рейтинга потребления;
:Отобразить рейтинг;
:Подготовить отчет по потреблению;
fork again
:Запрос на получение прогнозов потребления;
:Отобразить данные;
:Подготовить отчет по потреблению;

|Компания| 
fork again
:Запрос прогнозы по потреблению;
:Отобразить данные;
:Подготовить отчет по потреблению;
fork again
:Запрос на расчет изменению тарифа;
:Отобразить данные;
:Подготовить отчет по потреблению;

|Тех персонал|
fork again
:Подготовить отчета о состояние приборов;

|Система|
end fork
:;


'------------------------------ Отчет
|Система|
fork
:Сбор данных для составление отчета;
:Составление отчета;

|Домовладелец|
fork again
:Отображение отчета;
:Экспорт отчета;

|Администратор| 
fork again
:Отображение отчета;
:Экспорт отчета;

|Компания| 
fork again
:Отображение отчета;
:Экспорт отчета;

|Тех персонал|
fork again
:Отображение отчета;
:Экспорт отчета;


|Система|
end fork
stop
@enduml